DROP TABLE Mazo CASCADE CONSTRAINTS;
DROP TABLE Carta CASCADE CONSTRAINTS;
DROP TABLE Turno CASCADE CONSTRAINTS;
DROP TABLE Duelo CASCADE CONSTRAINTS;
DROP TABLE Jugador CASCADE CONSTRAINTS;
DROP TABLE CartaMostruo CASCADE CONSTRAINTS;
DROP TABLE CartaMagica CASCADE CONSTRAINTS;
DROP TABLE CartaTrampa CASCADE CONSTRAINTS;
DROP TABLE BarajaInicio CASCADE CONSTRAINTS;
DROP TABLE SobreExpansion CASCADE CONSTRAINTS;
DROP TABLE HistorialDuelos CASCADE CONSTRAINTS;
DROP TABLE PaqueteColeccionable CASCADE CONSTRAINTS;
/*SHOW ERRORS;*/

